name: 'Format PHP Code'
description: 'Runs composer run fmt'
inputs:
  path:
    description: 'Path to the php repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@f89a301251ea3f109745bab3a62be58575f216bf
      with:
        php-version: 8.2
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Run PHP Code Sniffer
      run: composer run fmt || true
      shell: bash
      working-directory: ${{ inputs.path }}
