<?php

/**
 * Capital API
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Adyen\Model\Capital;

use \ArrayAccess;
use \Adyen\Model\Capital\ObjectSerializer;

/**
 * Disbursement Class Doc Comment
 *
 * @package  Adyen\Model\Capital
 * @implements \ArrayAccess<string, mixed>
 */
class Disbursement implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Disbursement';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'accountHolderId' => 'string',
        'amount' => '\Adyen\Model\Capital\Amount',
        'balanceAccountId' => 'string',
        'balances' => '\Adyen\Model\Capital\Balance',
        'fee' => '\Adyen\Model\Capital\Fee',
        'fundsCollections' => '\Adyen\Model\Capital\FundsCollection[]',
        'grantId' => 'string',
        'id' => 'string',
        'repayment' => '\Adyen\Model\Capital\DisbursementRepayment'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'accountHolderId' => null,
        'amount' => null,
        'balanceAccountId' => null,
        'balances' => null,
        'fee' => null,
        'fundsCollections' => null,
        'grantId' => null,
        'id' => null,
        'repayment' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'accountHolderId' => false,
        'amount' => false,
        'balanceAccountId' => false,
        'balances' => false,
        'fee' => false,
        'fundsCollections' => false,
        'grantId' => false,
        'id' => false,
        'repayment' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'accountHolderId' => 'accountHolderId',
        'amount' => 'amount',
        'balanceAccountId' => 'balanceAccountId',
        'balances' => 'balances',
        'fee' => 'fee',
        'fundsCollections' => 'fundsCollections',
        'grantId' => 'grantId',
        'id' => 'id',
        'repayment' => 'repayment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'accountHolderId' => 'setAccountHolderId',
        'amount' => 'setAmount',
        'balanceAccountId' => 'setBalanceAccountId',
        'balances' => 'setBalances',
        'fee' => 'setFee',
        'fundsCollections' => 'setFundsCollections',
        'grantId' => 'setGrantId',
        'id' => 'setId',
        'repayment' => 'setRepayment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'accountHolderId' => 'getAccountHolderId',
        'amount' => 'getAmount',
        'balanceAccountId' => 'getBalanceAccountId',
        'balances' => 'getBalances',
        'fee' => 'getFee',
        'fundsCollections' => 'getFundsCollections',
        'grantId' => 'getGrantId',
        'id' => 'getId',
        'repayment' => 'getRepayment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('accountHolderId', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('balanceAccountId', $data ?? [], null);
        $this->setIfExists('balances', $data ?? [], null);
        $this->setIfExists('fee', $data ?? [], null);
        $this->setIfExists('fundsCollections', $data ?? [], null);
        $this->setIfExists('grantId', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('repayment', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        // An explicitly provided value (including null) always wins; the
        // default only applies when the field was omitted entirely.
        if (array_key_exists($variableName, $fields)) {
            $this->container[$variableName] = $fields[$variableName];
        } else {
            $this->container[$variableName] = $defaultValue;
        }
    }




    /**
     * Gets accountHolderId
     *
     * @return string
     */
    public function getAccountHolderId()
    {
        return $this->container['accountHolderId'];
    }

    /**
     * Sets accountHolderId
     *
     * @param string $accountHolderId The unique identifier of the account holder that received the disbursement.
     *
     * @return self
     */
    public function setAccountHolderId($accountHolderId): self
    {
        $this->container['accountHolderId'] = $accountHolderId;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return \Adyen\Model\Capital\Amount
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param \Adyen\Model\Capital\Amount $amount amount
     *
     * @return self
     */
    public function setAmount($amount): self
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets balanceAccountId
     *
     * @return string
     */
    public function getBalanceAccountId()
    {
        return $this->container['balanceAccountId'];
    }

    /**
     * Sets balanceAccountId
     *
     * @param string $balanceAccountId The unique identifier of the balance account that received the disbursement.
     *
     * @return self
     */
    public function setBalanceAccountId($balanceAccountId): self
    {
        $this->container['balanceAccountId'] = $balanceAccountId;

        return $this;
    }

    /**
     * Gets balances
     *
     * @return \Adyen\Model\Capital\Balance
     */
    public function getBalances()
    {
        return $this->container['balances'];
    }

    /**
     * Sets balances
     *
     * @param \Adyen\Model\Capital\Balance $balances balances
     *
     * @return self
     */
    public function setBalances($balances): self
    {
        $this->container['balances'] = $balances;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return \Adyen\Model\Capital\Fee
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param \Adyen\Model\Capital\Fee $fee fee
     *
     * @return self
     */
    public function setFee($fee): self
    {
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets fundsCollections
     *
     * @return \Adyen\Model\Capital\FundsCollection[]|null
     */
    public function getFundsCollections()
    {
        return $this->container['fundsCollections'];
    }

    /**
     * Sets fundsCollections
     *
     * @param \Adyen\Model\Capital\FundsCollection[]|null $fundsCollections Contains information about the accounts that Adyen uses to collect funds related to repayments.
     *
     * @return self
     */
    public function setFundsCollections($fundsCollections): self
    {
        $this->container['fundsCollections'] = $fundsCollections;

        return $this;
    }

    /**
     * Gets grantId
     *
     * @return string
     */
    public function getGrantId()
    {
        return $this->container['grantId'];
    }

    /**
     * Sets grantId
     *
     * @param string $grantId The unique identifier of the grant related to the disbursement.
     *
     * @return self
     */
    public function setGrantId($grantId): self
    {
        $this->container['grantId'] = $grantId;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The unique identifier of the disbursement.
     *
     * @return self
     */
    public function setId($id): self
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets repayment
     *
     * @return \Adyen\Model\Capital\DisbursementRepayment
     */
    public function getRepayment()
    {
        return $this->container['repayment'];
    }

    /**
     * Sets repayment
     *
     * @param \Adyen\Model\Capital\DisbursementRepayment $repayment repayment
     *
     * @return self
     */
    public function setRepayment($repayment): self
    {
        $this->container['repayment'] = $repayment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Returns an associative array of the model properties.
     *
     * @return array
     */
    public function toArray(): array
    {
        $array = [];
        foreach (self::$openAPITypes as $propertyName => $propertyType) {
            $propertyValue = $this[$propertyName];
            if ($propertyValue !== null) {
                // Check if the property value is an object and has a toArray() method
                if (is_object($propertyValue) && method_exists($propertyValue, 'toArray')) {
                    $array[$propertyName] = $propertyValue->toArray();
                // Check if it's type datetime
                } elseif ($propertyValue instanceof \DateTimeInterface) {
                    $array[$propertyName] = $propertyValue->format(DATE_ATOM);
                // If it's an array type we should check whether it contains objects and if so call toArray method
                } elseif (is_array($propertyValue)) {
                    $array[$propertyName] = array_map(function ($item) {
                        return $item instanceof ModelInterface ? $item->toArray() : $item;
                    }, $propertyValue);
                } else {
                    // Otherwise, directly assign the property value to the array
                    $array[$propertyName] = $propertyValue;
                }
            }
        }
        return $array;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
