<?php

/**
 * Configuration API
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Adyen\Model\BalancePlatform;

use \Adyen\Model\BalancePlatform\ObjectSerializer;

/**
 * ScaStatus Class Doc Comment
 *
 * @description The status of Strong Customer Authentication (SCA). Possible values: * **notPerformed**: the requester was unable to successfully authenticate the request using SCA, or has an SCA exemption. * **pending**: the request is pending SCA authentication. * **performed**: the request is successfully authenticated using SCA.
 * @package  Adyen\Model\BalancePlatform
 */
class ScaStatus
{
    /**
     * Possible values of this enum
     */
    public const NOT_PERFORMED = 'notPerformed';

    public const PENDING = 'pending';

    public const PERFORMED = 'performed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_PERFORMED,
            self::PENDING,
            self::PERFORMED
        ];
    }
}
