<?php

/**
 * Configuration API
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Adyen\Service\BalancePlatform;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Adyen\Configuration;
use Adyen\HeaderSelector;
use Adyen\BaseService;
use Adyen\Exception\AdyenException;
use Adyen\Model\BalancePlatform\ObjectSerializer;

/**
 * ManageCardPINApi Class
 *
 * @package  Adyen
 */
class ManageCardPINApi extends BaseService
{

    private const BASE_URL = 'https://balanceplatform-api-test.adyen.com/bcl/v2';

    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int|null Host index. Null means the host is selected by the configured environment.
     */
    protected $hostIndex;

    /**
     * @var string Base url
     */
    protected $baseURL;

    /** @var array<string, string[]> */
    public const CONTENT_TYPES = [
        'changeCardPin' => [
            'application/json',
        ],
        'publicKey' => [
            'application/json',
        ],
        'revealCardPin' => [
            'application/json',
        ],
    ];

    /**
     * ManageCardPINApi constructor
     *
     * @param Configuration|null $config
     * @param ClientInterface|null $client
     * @param HeaderSelector|null $selector
     * @param int|null $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec.
     *                            If null, the host matching the configured environment is selected.
     * @throws \Adyen\Exception\AdyenException
     */
    public function __construct(
        ?Configuration $config = null,
        ?ClientInterface $client = null,
        ?HeaderSelector $selector = null,
        ?int $hostIndex = null
    ) {
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        parent::__construct($this->config);
        $this->client = $client ?: new Client();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;

        // Create the baseUrl based on live/test and optional live-url-prefix
        $this->baseURL = $this->createBaseUrl(self::BASE_URL);
    }

    /**
     * Set the host index
     *
     * @param int|null $hostIndex Host index. Null restores selection by configured environment.
     */
    public function setHostIndex(?int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int|null Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation changeCardPin
     *
     * Change a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest pinChangeRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\BalancePlatform\PinChangeResponse
     */
    public function changeCardPin(\Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\BalancePlatform\PinChangeResponse
    {
        list($response) = $this->changeCardPinWithHttpInfo($pinChangeRequest, $requestOptions);
        return $response;
    }

    /**
     * Operation changeCardPinWithHttpInfo
     *
     * Change a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\BalancePlatform\PinChangeResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function changeCardPinWithHttpInfo(\Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['changeCardPin'][0];

        $request = $this->changeCardPinRequest($pinChangeRequest, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\BalancePlatform\PinChangeResponse',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\BalancePlatform\PinChangeResponse',
            $request,
            $response,
        );
    }

    /**
     * Operation changeCardPinAsync
     *
     * Change a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeCardPinAsync(\Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->changeCardPinAsyncWithHttpInfo($pinChangeRequest, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation changeCardPinAsyncWithHttpInfo
     *
     * Change a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function changeCardPinAsyncWithHttpInfo(\Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['changeCardPin'][0];

        $request = $this->changeCardPinRequest($pinChangeRequest, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\BalancePlatform\PinChangeResponse',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'changeCardPin'
     *
     * @param  \Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['changeCardPin'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function changeCardPinRequest(\Adyen\Model\BalancePlatform\PinChangeRequest $pinChangeRequest, string $contentType = self::CONTENT_TYPES['changeCardPin'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        $resourcePath = '/pins/change';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (isset($pinChangeRequest)) {
            $pinChangeRequest = $this->injectApplicationInfo($pinChangeRequest);
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($pinChangeRequest));
            } else {
                $httpBody = $pinChangeRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('clientKey');
        if ($apiKey !== null) {
            $queryParams['clientKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation publicKey
     *
     * Get an RSA public key
     *
     * @param  string|null $purpose The purpose of the public key.  Possible values: **pinChange**, **pinReveal**, **panReveal**.  Default value: **pinReveal**. (optional)
     * @param  string|null $format The encoding format of public key.  Possible values: **jwk**, **pem**.  Default value: **pem**. (optional)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\BalancePlatform\PublicKeyResponse
     */
    public function publicKey(?string $purpose = null, ?string $format = null, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\BalancePlatform\PublicKeyResponse
    {
        list($response) = $this->publicKeyWithHttpInfo($purpose, $format, $requestOptions);
        return $response;
    }

    /**
     * Operation publicKeyWithHttpInfo
     *
     * Get an RSA public key
     *
     * @param  string|null $purpose The purpose of the public key.  Possible values: **pinChange**, **pinReveal**, **panReveal**.  Default value: **pinReveal**. (optional)
     * @param  string|null $format The encoding format of public key.  Possible values: **jwk**, **pem**.  Default value: **pem**. (optional)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\BalancePlatform\PublicKeyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function publicKeyWithHttpInfo(?string $purpose = null, ?string $format = null, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['publicKey'][0];

        $request = $this->publicKeyRequest($purpose, $format, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\BalancePlatform\PublicKeyResponse',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\BalancePlatform\PublicKeyResponse',
            $request,
            $response,
        );
    }

    /**
     * Operation publicKeyAsync
     *
     * Get an RSA public key
     *
     * @param  string|null $purpose The purpose of the public key.  Possible values: **pinChange**, **pinReveal**, **panReveal**.  Default value: **pinReveal**. (optional)
     * @param  string|null $format The encoding format of public key.  Possible values: **jwk**, **pem**.  Default value: **pem**. (optional)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function publicKeyAsync(?string $purpose = null, ?string $format = null, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->publicKeyAsyncWithHttpInfo($purpose, $format, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation publicKeyAsyncWithHttpInfo
     *
     * Get an RSA public key
     *
     * @param  string|null $purpose The purpose of the public key.  Possible values: **pinChange**, **pinReveal**, **panReveal**.  Default value: **pinReveal**. (optional)
     * @param  string|null $format The encoding format of public key.  Possible values: **jwk**, **pem**.  Default value: **pem**. (optional)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function publicKeyAsyncWithHttpInfo(?string $purpose = null, ?string $format = null, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['publicKey'][0];

        $request = $this->publicKeyRequest($purpose, $format, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\BalancePlatform\PublicKeyResponse',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'publicKey'
     *
     * @param  string|null $purpose The purpose of the public key.  Possible values: **pinChange**, **pinReveal**, **panReveal**.  Default value: **pinReveal**. (optional)
     * @param  string|null $format The encoding format of public key.  Possible values: **jwk**, **pem**.  Default value: **pem**. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['publicKey'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function publicKeyRequest(?string $purpose = null, ?string $format = null, string $contentType = self::CONTENT_TYPES['publicKey'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        $resourcePath = '/publicKey';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $purpose,
            'purpose', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('clientKey');
        if ($apiKey !== null) {
            $queryParams['clientKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation revealCardPin
     *
     * Reveal a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest revealPinRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\BalancePlatform\RevealPinResponse
     */
    public function revealCardPin(\Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\BalancePlatform\RevealPinResponse
    {
        list($response) = $this->revealCardPinWithHttpInfo($revealPinRequest, $requestOptions);
        return $response;
    }

    /**
     * Operation revealCardPinWithHttpInfo
     *
     * Reveal a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\BalancePlatform\RevealPinResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function revealCardPinWithHttpInfo(\Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['revealCardPin'][0];

        $request = $this->revealCardPinRequest($revealPinRequest, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\BalancePlatform\RevealPinResponse',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\BalancePlatform\RevealPinResponse',
            $request,
            $response,
        );
    }

    /**
     * Operation revealCardPinAsync
     *
     * Reveal a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revealCardPinAsync(\Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->revealCardPinAsyncWithHttpInfo($revealPinRequest, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation revealCardPinAsyncWithHttpInfo
     *
     * Reveal a card PIN
     *
     * @param  \Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revealCardPinAsyncWithHttpInfo(\Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['revealCardPin'][0];

        $request = $this->revealCardPinRequest($revealPinRequest, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\BalancePlatform\RevealPinResponse',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'revealCardPin'
     *
     * @param  \Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['revealCardPin'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function revealCardPinRequest(\Adyen\Model\BalancePlatform\RevealPinRequest $revealPinRequest, string $contentType = self::CONTENT_TYPES['revealCardPin'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        $resourcePath = '/pins/reveal';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (isset($revealPinRequest)) {
            $revealPinRequest = $this->injectApplicationInfo($revealPinRequest);
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($revealPinRequest));
            } else {
                $httpBody = $revealPinRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('clientKey');
        if ($apiKey !== null) {
            $queryParams['clientKey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [
            RequestOptions::HTTP_ERRORS => false // prevent Guzzle default behaviour throwing exceptions on 4xx/5xx responses
        ];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    // unexpected parsing error
                    throw new AdyenException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
                $content = json_decode(json_encode($content), false);
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
