<?php

/**
 * Management API
 *
 * The version of the OpenAPI document: 3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Adyen\Service\Management;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Adyen\Configuration;
use Adyen\HeaderSelector;
use Adyen\BaseService;
use Adyen\Exception\AdyenException;
use Adyen\Model\Management\ObjectSerializer;

/**
 * AllowedOriginsCompanyLevelApi Class
 *
 * @package  Adyen
 */
class AllowedOriginsCompanyLevelApi extends BaseService
{

    private const BASE_URL = 'https://management-test.adyen.com/v3';

    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int|null Host index. Null means the host is selected by the configured environment.
     */
    protected $hostIndex;

    /**
     * @var string Base url
     */
    protected $baseURL;

    /** @var array<string, string[]> */
    public const CONTENT_TYPES = [
        'createAllowedOrigin' => [
            'application/json',
        ],
        'deleteAllowedOrigin' => [
            'application/json',
        ],
        'getAllowedOrigin' => [
            'application/json',
        ],
        'listAllowedOrigins' => [
            'application/json',
        ],
    ];

    /**
     * AllowedOriginsCompanyLevelApi constructor
     *
     * @param Configuration|null $config
     * @param ClientInterface|null $client
     * @param HeaderSelector|null $selector
     * @param int|null $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec.
     *                            If null, the host matching the configured environment is selected.
     * @throws \Adyen\Exception\AdyenException
     */
    public function __construct(
        ?Configuration $config = null,
        ?ClientInterface $client = null,
        ?HeaderSelector $selector = null,
        ?int $hostIndex = null
    ) {
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        parent::__construct($this->config);
        $this->client = $client ?: new Client();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;

        // Create the baseUrl based on live/test and optional live-url-prefix
        $this->baseURL = $this->createBaseUrl(self::BASE_URL);
    }

    /**
     * Set the host index
     *
     * @param int|null $hostIndex Host index. Null restores selection by configured environment.
     */
    public function setHostIndex(?int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int|null Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAllowedOrigin
     *
     * Create an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\Model\Management\AllowedOrigin $allowedOrigin allowedOrigin (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\Management\AllowedOrigin
     */
    public function createAllowedOrigin(string $companyId, string $apiCredentialId, \Adyen\Model\Management\AllowedOrigin $allowedOrigin, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\Management\AllowedOrigin
    {
        list($response) = $this->createAllowedOriginWithHttpInfo($companyId, $apiCredentialId, $allowedOrigin, $requestOptions);
        return $response;
    }

    /**
     * Operation createAllowedOriginWithHttpInfo
     *
     * Create an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\Model\Management\AllowedOrigin $allowedOrigin (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\Management\AllowedOrigin, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAllowedOriginWithHttpInfo(string $companyId, string $apiCredentialId, \Adyen\Model\Management\AllowedOrigin $allowedOrigin, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['createAllowedOrigin'][0];

        $request = $this->createAllowedOriginRequest($companyId, $apiCredentialId, $allowedOrigin, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\Management\AllowedOrigin',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\Management\AllowedOrigin',
            $request,
            $response,
        );
    }

    /**
     * Operation createAllowedOriginAsync
     *
     * Create an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\Model\Management\AllowedOrigin $allowedOrigin (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAllowedOriginAsync(string $companyId, string $apiCredentialId, \Adyen\Model\Management\AllowedOrigin $allowedOrigin, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->createAllowedOriginAsyncWithHttpInfo($companyId, $apiCredentialId, $allowedOrigin, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAllowedOriginAsyncWithHttpInfo
     *
     * Create an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\Model\Management\AllowedOrigin $allowedOrigin (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAllowedOriginAsyncWithHttpInfo(string $companyId, string $apiCredentialId, \Adyen\Model\Management\AllowedOrigin $allowedOrigin, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['createAllowedOrigin'][0];

        $request = $this->createAllowedOriginRequest($companyId, $apiCredentialId, $allowedOrigin, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\Management\AllowedOrigin',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAllowedOrigin'
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\Model\Management\AllowedOrigin $allowedOrigin (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['createAllowedOrigin'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAllowedOriginRequest(string $companyId, string $apiCredentialId, \Adyen\Model\Management\AllowedOrigin $allowedOrigin, string $contentType = self::CONTENT_TYPES['createAllowedOrigin'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        // verify the required parameter 'companyId' is set
        if ($companyId === null || (is_array($companyId) && count($companyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $companyId when calling createAllowedOrigin'
            );
        }

        // verify the required parameter 'apiCredentialId' is set
        if ($apiCredentialId === null || (is_array($apiCredentialId) && count($apiCredentialId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $apiCredentialId when calling createAllowedOrigin'
            );
        }

        $resourcePath = '/companies/{companyId}/apiCredentials/{apiCredentialId}/allowedOrigins';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($companyId !== null) {
            $resourcePath = str_replace(
                '{' . 'companyId' . '}',
                ObjectSerializer::toPathValue($companyId),
                $resourcePath
            );
        }

        // path params
        if ($apiCredentialId !== null) {
            $resourcePath = str_replace(
                '{' . 'apiCredentialId' . '}',
                ObjectSerializer::toPathValue($apiCredentialId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (isset($allowedOrigin)) {
            $allowedOrigin = $this->injectApplicationInfo($allowedOrigin);
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($allowedOrigin));
            } else {
                $httpBody = $allowedOrigin;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteAllowedOrigin
     *
     * Delete an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteAllowedOrigin(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): void
    {
        $this->deleteAllowedOriginWithHttpInfo($companyId, $apiCredentialId, $originId, $requestOptions);
    }

    /**
     * Operation deleteAllowedOriginWithHttpInfo
     *
     * Delete an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAllowedOriginWithHttpInfo(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['deleteAllowedOrigin'][0];

        $request = $this->deleteAllowedOriginRequest($companyId, $apiCredentialId, $originId, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        return [null, $statusCode, $response->getHeaders()];
    }

    /**
     * Operation deleteAllowedOriginAsync
     *
     * Delete an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAllowedOriginAsync(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->deleteAllowedOriginAsyncWithHttpInfo($companyId, $apiCredentialId, $originId, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAllowedOriginAsyncWithHttpInfo
     *
     * Delete an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAllowedOriginAsyncWithHttpInfo(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['deleteAllowedOrigin'][0];

        $request = $this->deleteAllowedOriginRequest($companyId, $apiCredentialId, $originId, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAllowedOrigin'
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['deleteAllowedOrigin'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteAllowedOriginRequest(string $companyId, string $apiCredentialId, string $originId, string $contentType = self::CONTENT_TYPES['deleteAllowedOrigin'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        // verify the required parameter 'companyId' is set
        if ($companyId === null || (is_array($companyId) && count($companyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $companyId when calling deleteAllowedOrigin'
            );
        }

        // verify the required parameter 'apiCredentialId' is set
        if ($apiCredentialId === null || (is_array($apiCredentialId) && count($apiCredentialId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $apiCredentialId when calling deleteAllowedOrigin'
            );
        }

        // verify the required parameter 'originId' is set
        if ($originId === null || (is_array($originId) && count($originId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $originId when calling deleteAllowedOrigin'
            );
        }

        $resourcePath = '/companies/{companyId}/apiCredentials/{apiCredentialId}/allowedOrigins/{originId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($companyId !== null) {
            $resourcePath = str_replace(
                '{' . 'companyId' . '}',
                ObjectSerializer::toPathValue($companyId),
                $resourcePath
            );
        }

        // path params
        if ($apiCredentialId !== null) {
            $resourcePath = str_replace(
                '{' . 'apiCredentialId' . '}',
                ObjectSerializer::toPathValue($apiCredentialId),
                $resourcePath
            );
        }

        // path params
        if ($originId !== null) {
            $resourcePath = str_replace(
                '{' . 'originId' . '}',
                ObjectSerializer::toPathValue($originId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllowedOrigin
     *
     * Get an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\Management\AllowedOrigin
     */
    public function getAllowedOrigin(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\Management\AllowedOrigin
    {
        list($response) = $this->getAllowedOriginWithHttpInfo($companyId, $apiCredentialId, $originId, $requestOptions);
        return $response;
    }

    /**
     * Operation getAllowedOriginWithHttpInfo
     *
     * Get an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\Management\AllowedOrigin, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllowedOriginWithHttpInfo(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['getAllowedOrigin'][0];

        $request = $this->getAllowedOriginRequest($companyId, $apiCredentialId, $originId, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\Management\AllowedOrigin',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\Management\AllowedOrigin',
            $request,
            $response,
        );
    }

    /**
     * Operation getAllowedOriginAsync
     *
     * Get an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllowedOriginAsync(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->getAllowedOriginAsyncWithHttpInfo($companyId, $apiCredentialId, $originId, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllowedOriginAsyncWithHttpInfo
     *
     * Get an allowed origin
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllowedOriginAsyncWithHttpInfo(string $companyId, string $apiCredentialId, string $originId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['getAllowedOrigin'][0];

        $request = $this->getAllowedOriginRequest($companyId, $apiCredentialId, $originId, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\Management\AllowedOrigin',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllowedOrigin'
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $originId Unique identifier of the allowed origin. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['getAllowedOrigin'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllowedOriginRequest(string $companyId, string $apiCredentialId, string $originId, string $contentType = self::CONTENT_TYPES['getAllowedOrigin'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        // verify the required parameter 'companyId' is set
        if ($companyId === null || (is_array($companyId) && count($companyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $companyId when calling getAllowedOrigin'
            );
        }

        // verify the required parameter 'apiCredentialId' is set
        if ($apiCredentialId === null || (is_array($apiCredentialId) && count($apiCredentialId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $apiCredentialId when calling getAllowedOrigin'
            );
        }

        // verify the required parameter 'originId' is set
        if ($originId === null || (is_array($originId) && count($originId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $originId when calling getAllowedOrigin'
            );
        }

        $resourcePath = '/companies/{companyId}/apiCredentials/{apiCredentialId}/allowedOrigins/{originId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($companyId !== null) {
            $resourcePath = str_replace(
                '{' . 'companyId' . '}',
                ObjectSerializer::toPathValue($companyId),
                $resourcePath
            );
        }

        // path params
        if ($apiCredentialId !== null) {
            $resourcePath = str_replace(
                '{' . 'apiCredentialId' . '}',
                ObjectSerializer::toPathValue($apiCredentialId),
                $resourcePath
            );
        }

        // path params
        if ($originId !== null) {
            $resourcePath = str_replace(
                '{' . 'originId' . '}',
                ObjectSerializer::toPathValue($originId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAllowedOrigins
     *
     * Get a list of allowed origins
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Adyen\Model\Management\AllowedOriginsResponse
     */
    public function listAllowedOrigins(string $companyId, string $apiCredentialId, ?\Adyen\RequestOptions $requestOptions = null): \Adyen\Model\Management\AllowedOriginsResponse
    {
        list($response) = $this->listAllowedOriginsWithHttpInfo($companyId, $apiCredentialId, $requestOptions);
        return $response;
    }

    /**
     * Operation listAllowedOriginsWithHttpInfo
     *
     * Get a list of allowed origins
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \Adyen\Exception\AdyenException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Adyen\Model\Management\AllowedOriginsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAllowedOriginsWithHttpInfo(string $companyId, string $apiCredentialId, ?\Adyen\RequestOptions $requestOptions = null): array
    {
        $contentType = self::CONTENT_TYPES['listAllowedOrigins'][0];

        $request = $this->listAllowedOriginsRequest($companyId, $apiCredentialId, $contentType, $requestOptions);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            if ($e->hasResponse()) {
                $response = $e->getResponse();
                throw AdyenException::fromResponse(
                    $response->getStatusCode(),
                    $response->getHeaders(),
                    (string) $response->getBody(),
                    $e
                );
            }

            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        } catch (ConnectException $e) {
            throw new AdyenException(
                "[{$e->getCode()}] {$e->getMessage()}",
                (int) $e->getCode(),
                [],
                null,
                $e
            );
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw AdyenException::fromResponse(
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }


        switch ($statusCode) {
            case 200:
                return $this->handleResponseWithDataType(
                    '\Adyen\Model\Management\AllowedOriginsResponse',
                    $request,
                    $response,
                );
        }



        return $this->handleResponseWithDataType(
            '\Adyen\Model\Management\AllowedOriginsResponse',
            $request,
            $response,
        );
    }

    /**
     * Operation listAllowedOriginsAsync
     *
     * Get a list of allowed origins
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAllowedOriginsAsync(string $companyId, string $apiCredentialId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->listAllowedOriginsAsyncWithHttpInfo($companyId, $apiCredentialId, $requestOptions)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAllowedOriginsAsyncWithHttpInfo
     *
     * Get a list of allowed origins
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  \Adyen\RequestOptions|null $requestOptions Additional request options (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAllowedOriginsAsyncWithHttpInfo(string $companyId, string $apiCredentialId, ?\Adyen\RequestOptions $requestOptions = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $contentType = self::CONTENT_TYPES['listAllowedOrigins'][0];

        $request = $this->listAllowedOriginsRequest($companyId, $apiCredentialId, $contentType, $requestOptions);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($request) {
                    $statusCode = $response->getStatusCode();
                    if ($statusCode < 200 || $statusCode > 299) {
                        throw AdyenException::fromResponse(
                            $statusCode,
                            $response->getHeaders(),
                            (string) $response->getBody()
                        );
                    }

                    return $this->handleResponseWithDataType(
                        '\Adyen\Model\Management\AllowedOriginsResponse',
                        $request,
                        $response
                    );
                },
                function ($exception) {
                    if ($exception instanceof RequestException && $exception->hasResponse()) {
                        $response = $exception->getResponse();
                        throw AdyenException::fromResponse(
                            $response->getStatusCode(),
                            $response->getHeaders(),
                            (string) $response->getBody(),
                            $exception
                        );
                    }

                    throw new AdyenException(
                        "[{$exception->getCode()}] {$exception->getMessage()}",
                        (int) $exception->getCode(),
                        [],
                        null,
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAllowedOrigins'
     *
     * @param  string $companyId The unique identifier of the company account. (required)
     * @param  string $apiCredentialId Unique identifier of the API credential. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::CONTENT_TYPES['listAllowedOrigins'] to see the possible values for this operation
     * @param \Adyen\RequestOptions|null $requestOptions
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAllowedOriginsRequest(string $companyId, string $apiCredentialId, string $contentType = self::CONTENT_TYPES['listAllowedOrigins'][0], ?\Adyen\RequestOptions $requestOptions = null): Request
    {

        // verify the required parameter 'companyId' is set
        if ($companyId === null || (is_array($companyId) && count($companyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $companyId when calling listAllowedOrigins'
            );
        }

        // verify the required parameter 'apiCredentialId' is set
        if ($apiCredentialId === null || (is_array($apiCredentialId) && count($apiCredentialId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $apiCredentialId when calling listAllowedOrigins'
            );
        }

        $resourcePath = '/companies/{companyId}/apiCredentials/{apiCredentialId}/allowedOrigins';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($companyId !== null) {
            $resourcePath = str_replace(
                '{' . 'companyId' . '}',
                ObjectSerializer::toPathValue($companyId),
                $resourcePath
            );
        }

        // path params
        if ($apiCredentialId !== null) {
            $resourcePath = str_replace(
                '{' . 'apiCredentialId' . '}',
                ObjectSerializer::toPathValue($apiCredentialId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart,
            $requestOptions
        );

        $headers['adyen-library-name'] = $this->config->getLibraryName();
        $headers['adyen-library-version'] = $this->config->getLibraryVersion();

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) && !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->baseURL;
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [
            RequestOptions::HTTP_ERRORS => false // prevent Guzzle default behaviour throwing exceptions on 4xx/5xx responses
        ];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    // unexpected parsing error
                    throw new AdyenException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
                $content = json_decode(json_encode($content), false);
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
