name: Automatic Github release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  github:
    permissions:
      contents: write
    uses: Adyen/release-automation-action/.github/workflows/reusable-github-release.yml@v1.3.1
    with:
      release-title: Adyen PHP API Library
      develop-branch: main
    secrets:
      token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
